### ISSUE TITLE
NS 3.0 webpack issue

### ISSUE THREAD

**Issue by Jaishankarb** [PeterStaev/NativeScript-Drop-Down#110]
nativescript-drop-down plugin version : 3.1.0 

while running web pack command: npm run build-android-bundle, used to get the below error:

:asbg:generateBindings
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
D:\Development_Avecto\bcbs\MyBlue\platforms\android\src\main\java\com\tns\gen\android\widget\Spinner_frnal_ts_helpers_l58_c38__TNSSpinner.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:59)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED

Also tested with 3.0.2 version too. The same problem exists.

**Comment by PeterStaev** [comment]
@Jaishankarb this is a know problem with TNS 3.0 that should be fixed with TNS 3.1. In order to solve it you need to do `tns platform clean android` and then run your app.
