### ISSUE TITLE
Angular 8 NativeScript 6 Issue

### ISSUE THREAD

**Issue by 59-dev** [PeterStaev/NativeScript-Drop-Down#226]
Greetings,  

I'm working with NativeScript 6 and Angular 8 and wanted to implement the Drop-Down plugin.  However, I keep getting the following error.  I have followed the documentation and read the ReadMe for the plugin but am still having issues.  The repository below is a an reproduction of the error & below that is the error that I get when I am running in tns preview.  Can anyone assist?  Does the plugin even support NG8?

https://github.com/59-dev/Angular8TNSDD

 CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:4160:24: ERROR Error: Uncaught (in promise): Error: DropDown(1) is not a valid View instance.
at _addView(file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:415:22) [angular]
at addChild(file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:44:18) [angular]
at addChild(file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base.js:13:35) [angular]
at insertToLayout(file:///app/tns_modules/nativescript-angular/view-util.js:98:22) [angular]
at addToVisualTree(file:///app/tns_modules/nativescript-angular/view-util.js:79:26) [angular]
at insertChild(file:///app/tns_modules/nativescript-angular/view-util.js:41:27) [angular]
at appendChild(file:///app/tns_modules/nativescript-angular/renderer.js:87:30) [angular]
at appendChild(file:///app/tns_modules/@angular/core/bundles/core.umd.js:30522:32) [angular]
at createElement(file:///app/tns_modules/@angular/core/bundles/core.umd.js:28530:29) [angular]
at createViewNodes(file:///app/tns_modules/@angular/core/bundles/core.umd.js:29462:33) [angular]
at callViewAction(file:///app/tns_modules/@angular/core/bundles/core.umd.js:29817:24) [angular]
at execComponentViewsAction(file:///app/tns_modules/@angular/core/bundles/core.umd.js:29736:25) [angular]
at createViewNodes(file:///app/tns_modules/@angular/core/bundles/core.umd.js:29529:29) [angular]
at createRootView(file:///app/tns_modules/@angular/core/bundles/core.umd.js:29415:20) [angular]
at callWithDebugContext(file:///app/tns_modules/@angular/core/bundles/core.umd.js:30423:28) [angular]
at create(file:///app/tns_modules/@angular/core/bundles/core.umd.js:20648:41) [angular]
at createComponent(file:///app/tns_modules/@angular/core/bundles/core.umd.js:20759:49) [angular]
at loadWithFactory(file:///app/tns_modules/nativescript-angular/common/detached-loader.js:38:45) [angular]
at activateOnGoForward(file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:283:56) [angular]
at activateWith(file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:261:29) [angular]
at activateRoutes(file:///app/tns_modules/@angular/router/bundles/router.umd.js:2496:42) [angular]
at file:///app/tns_modules/@angular/router/bundles/router.umd.js:2447:29 [angular]
at forEach([native code]) [angular]
at activateChildRoutes(file:///app/tns_modules/@angular/router/bundles/router.umd.js:2446:34) [angular]
at activateRoutes(file:///app/tns_modules/@angular/router/bundles/router.umd.js:2503:35) [angular]
at file:///app/tns_modules/@angular/router/bundles/router.umd.js:2447:29 [angular]
at forEach([native code]) [angular]
at activateChildRoutes(file:///app/tns_modules/@angular/router/bundles/router.umd.js:2446:34) [angular]
at activate(file:///app/tns_modules/@angular/router/bundles/router.umd.js:2371:31) [angular]
at file:///app/tns_modules/@angular/router/bundles/router.umd.js:2355:15 [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/map.js:49:33) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/tap.js:65:26) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/map.js:55:26) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at notifyNext(file:///app/tns_modules/rxjs/internal/operators/switchMap.js:86:26) [angular]
at _next(file:///app/tns_modules/rxjs/internal/InnerSubscriber.js:28:27) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/map.js:55:26) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at file:///app/tns_modules/rxjs/internal/util/subscribeToArray.js:5:22 [angular]
at _trySubscribe(file:///app/tns_modules/rxjs/internal/Observable.js:44:29) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:30:25) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:25:29) [angular]
at _innerSub(file:///app/tns_modules/rxjs/internal/operators/switchMap.js:65:67) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/switchMap.js:55:19) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at notifyNext(file:///app/tns_modules/rxjs/internal/operators/switchMap.js:86:26) [angular]
at _next(file:///app/tns_modules/rxjs/internal/InnerSubscriber.js:28:27) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/map.js:55:26) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/tap.js:65:26) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at notifyNext(file:///app/tns_modules/rxjs/internal/operators/mergeMap.js:92:26) [angular]
at _next(file:///app/tns_modules/rxjs/internal/InnerSubscriber.js:28:27) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/map.js:55:26) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _complete(file:///app/tns_modules/rxjs/internal/operators/takeLast.js:71:25) [angular]
at complete(file:///app/tns_modules/rxjs/internal/Subscriber.js:78:21) [angular]
at _complete(file:///app/tns_modules/rxjs/internal/Subscriber.js:96:30) [angular]
at complete(file:///app/tns_modules/rxjs/internal/Subscriber.js:78:21) [angular]
at _complete(file:///app/tns_modules/rxjs/internal/operators/mergeMap.js:87:32) [angular]
at complete(file:///app/tns_modules/rxjs/internal/Subscriber.js:78:21) [angular]
at file:///app/tns_modules/rxjs/internal/util/subscribeToArray.js:7:24 [angular]
at _trySubscribe(file:///app/tns_modules/rxjs/internal/Observable.js:44:29) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:30:25) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:25:29) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:25:29) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:25:29) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:25:29) [angular]
at _innerSub(file:///app/tns_modules/rxjs/internal/operators/mergeMap.js:82:42) [angular]
at _tryNext(file:///app/tns_modules/rxjs/internal/operators/mergeMap.js:76:19) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/mergeMap.js:59:20) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/tap.js:65:26) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at file:///app/tns_modules/rxjs/internal/util/subscribeToArray.js:5:22 [angular]
at _trySubscribe(file:///app/tns_modules/rxjs/internal/Observable.js:44:29) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:30:25) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:25:29) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:25:29) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:25:29) [angular]
at subscribe(file:///app/tns_modules/rxjs/internal/Observable.js:25:29) [angular]
at _innerSub(file:///app/tns_modules/rxjs/internal/operators/switchMap.js:65:67) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/switchMap.js:55:19) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/filter.js:52:28) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/tap.js:65:26) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/tap.js:65:26) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at notifyNext(file:///app/tns_modules/rxjs/internal/operators/mergeMap.js:92:26) [angular]
at _next(file:///app/tns_modules/rxjs/internal/InnerSubscriber.js:28:27) [angular]
at next(file:///app/tns_modules/rxjs/internal/Subscriber.js:66:17) [angular]
at _next(file:///app/tns_modules/rxjs/internal/operators/map.js:55:26) [angular]

**Comment by PeterStaev** [comment]
Hey @59-dev , from what I see you aren't importing the `DropDownModule` in the module where you use it (home module). You are just importing it in the app module.

**Comment by 59-dev** [comment]
@PeterStaev If you look at the updated repo, you will see that adding the module does not fix the issue.

**Comment by PeterStaev** [comment]
I just cloned the new repo, and everything works perfectly fine on both iOS and android.

**Comment by 59-dev** [comment]
@PeterStaev I am using tns preview and the Playground app with an iOS device.  Maybe that's the difference?

**Comment by PeterStaev** [comment]
No idea as I have never used personally preview. I know when setting up on the playground there are some specifics how you add you add and use your packages, but not sure about `tns preview`.

**Comment by 59-dev** [comment]
@PeterStaev tns preview generates the QR code in your IDE terminal so that you can scann it using the Playground App.  I'll look for that documentation on setting up the Drop-Down on playground or PM you if I can't find it.

**Comment by 59-dev** [comment]
@PeterStaev I am still having issues unfortunately.  Can you try to replicate this issue using tns preview from the NS CLI?

**Comment by PeterStaev** [comment]
@59-dev , I can simulate the problem, but I'm not sure if the preview is intended to work with plugins or it is just for built in controls. 

So I would strongly suggest you use normal `tns run` instead of the preview command.

**Comment by 59-dev** [comment]
Thank you!

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please provide more details.
