### ISSUE TITLE
Setting the default item in Android

### ISSUE THREAD

**Issue by ahmedelgendy** [PeterStaev/NativeScript-Drop-Down#24]
I want to set default item for Android
although my code looks like this
`<DropDown #dd [items]="genders" [selectedIndex]="defaultIndex" 
            (selectedIndexChange)="onchange(dd.selectedIndex)"></DropDown>`
Android UI looks empty, has no default value like the image
<img width="389" alt="screen shot 2016-07-18 at 7 22 28 am" src="https://cloud.githubusercontent.com/assets/6203118/16906034/ad97409c-4cb8-11e6-8c4c-26f9131a05e7.png">
IOS works fine with the default value

**Comment by ryc16** [comment]
What is the empty row on the top of dropdown in android? It is not clickable so what is the purpose? Not sure if it was there before.

**Comment by SjurWarEagle** [comment]
It is the hint (settable property) of the drop down box.

**Comment by ryc16** [comment]
Thanks @SjurWarEagle,

Do you mean this?
`<dd:DropDown items="{{ items }}" hint="test" selectedIndex="{{ selectedIndex }}" row="0" colSpan="2"  />
`

After I add hint to the example, I got RuntimeException:

```
W/System.err( 2903): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demodropdown/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
W/System.err( 2903): Calling js method onCreate failed
W/System.err( 2903): Error: Building UI from XML. @file:///app/main-page.xml:3:5
W/System.err( 2903):  ↳Cannot read property 'getAdapter' of undefined
W/System.err( 2903): File: "/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/builder/builder.js, line: 162, column: 20
W/System.err( 2903): StackTrace:
W/System.err( 2903):    Frame: function:'', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/builder/builder.js', line: 162, column: 21
W/System.err( 2903):    Frame: function:'', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/xml/xml.js', line: 148, column: 13
W/System.err( 2903):    Frame: function:'EasySAXParser.parse', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/js-libs/easysax/easysax.js', line: 751, column: 23
W/System.err( 2903):    Frame: function:'XmlParser.parse', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/xml/xml.js', line: 195, column: 22
W/System.err( 2903):    Frame: function:'XmlStringParser.parse', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/builder/builder.js', line: 168, column: 27
W/System.err( 2903):    Frame: function:'parseInternal', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/builder/builder.js', line: 43, column: 11
W/System.err( 2903):    Frame: function:'loadInternal', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/builder/builder.js', line: 120, column: 27
W/System.err( 2903):    Frame: function:'load', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/builder/builder.js', line: 104, column: 27
W/System.err( 2903):    Frame: function:'pageFromBuilder', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/frame/frame-common.js', line: 111, column: 27
W/System.err( 2903):    Frame: function:'resolvePageFromEntry', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/frame/frame-common.js', line: 89, column: 20
W/System.err( 2903):    Frame: function:'Frame.navigate', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/frame/frame-common.js', line: 165, column: 20
W/System.err( 2903):    Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/frame/frame.js', line: 690, column: 19
W/System.err( 2903):    Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/org.nativescript.demodropdown/files/app/tns_modules/ui/frame/activity.js', line: 12, column: 25
W/System.err( 2903):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
W/System.err( 2903):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
W/System.err( 2903):    at android.app.ActivityThread.access$800(ActivityThread.java:135)
W/System.err( 2903):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
W/System.err( 2903):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 2903):    at android.os.Looper.loop(Looper.java:136)
W/System.err( 2903):    at android.app.ActivityThread.main(ActivityThread.java:5017)
W/System.err( 2903):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 2903):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 2903):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
W/System.err( 2903):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
W/System.err( 2903):    at dalvik.system.NativeStart.main(Native Method)
```

Assume it works and it is for hint, when there is no hint, does it make more sense not to show empty row.

**Comment by SjurWarEagle** [comment]
Yes, I have the same problem:
https://github.com/PeterStaev/NativeScript-Drop-Down/issues/21

**Comment by SjurWarEagle** [comment]
@ahmedelgendy 
I had setting the default selection on my todolist for my current app and took a look into it.


This patch for the Drop Down has fixed it for me.


```
===================================================================
--- NativeScript-Drop-Down/drop-down-common.ts	(revision c8af07d67a8418a8d899365f2b5e6ff6dfe96f8b)
+++ NativeScript-Drop-Down/drop-down-common.ts	(revision )
@@ -107,7 +107,7 @@
             return;
         }
 
-        if (index < 0 || index >= this.items.length) {
+        if (index < 0 || (this.items && index >= this.items.length)) {
             this.selectedIndex = undefined;
             throw new Error("selectedIndex should be between [0, items.length - 1]");
         }

```

Note: Because NativeScript-Drop-Down adds the hint to the list, the first element with index 0 is the hint, yo your first added element is 1. 
So normally you would write
        this.selectedIndexDays = 0;
        this.selectedIndexLocations = 0;
        this.selectedIndexLanguages = 0;
but this would select the hint for the dropdowns.
You have to use for android.
        this.selectedIndexDays = 1;
        this.selectedIndexLocations = 1;
        this.selectedIndexLanguages = 1;
I agree this is ugly as.... and I hope PeterStaev has a better solution for the problem of not able to set the selectedIndex on android.

**Comment by PeterStaev** [comment]
Hey guys, this should be fixed in the new version on npm.
